### ISSUE TITLE
Recomendation for SRP and DIP in class Point

### ISSUE THREAD

**Issue by DJavierReyesM** [jethronap/PlaygroungOfTheEarth#7]
Here's a recommendation for your great work: The Point class violates the SRP since the Factory class should be outside the Point class to keep the Factory responsibilities for creating more focused points separate, and the Point responsibilities for providing the initial template for point objects. In the same way, there is a violation of DIP since Point is depending on a static class, that is, on a concretion for the generation / representation of polar or Cartesian points. The proposed solution to correct SRP is to separate the responsibilities of Point, leaving it as a class that serves as an initial template for the points. To correct DIP there are several options, but we have chosen to do the following: eliminate the newCartesianPoint () method and represent it as the toString of the Point class since the X and Y coordinates refer to the coordinate axes; Finally, Factory is eliminated and an interface called PolarOperations is created that will handle all the polar operations that can be carried out, which will have polarTransformation () as its initial abstract method, which will allow the transformation of the Cartesian point into polar. With this Point will depend on an abstraction and not on a concretion.

 * @author Javier Reyes
"Code for Point:
public class Point implements PolarOperations{

    private double x, y;

    public Point(double x, double y) {
        this.x = x;
        this.y = y;
    }       
    public String toString(){
        return  "Point: (x,y) = ("+this.x+","+this.y+")";
    		
    }
    public void setX(double x){
        this.x=x;
    }
    public void setY(double y){
        this.y=y;
    }
    public double getX(){
        return x;
    }
    public double getY(){
        return y;
    }
    @Override
    public void polarTransform() {
        double cartesianX= getX();
        double cartesianY= getY();
        setY(cartesianX*Math.sin(cartesianY));
        setX(cartesianX*Math.cos(cartesianY));        
        System.out.println("PolarPoint: (rho,theta) = ("+x+","+y+")");
        
    }
}
 "

"Code for interface:
 */
public interface PolarOperations {
    void polarTransform();
}

![Blank diagram (2)](https://user-images.githubusercontent.com/73187395/99893172-dce30680-2c4a-11eb-8f03-1cb41f1ee83e.png)

**Comment by jethronap** [comment]
Thanks again!
